ad_le_bts_sio:
    resource: "@ADLeBtsSioBundle/Resources/config/routing.yml"
    prefix:   /

a_dtest2:
    resource: "@ADtest2Bundle/Resources/config/routing.yml"
    prefix:   /
    
   
    
   

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    pattern:   /login
    defaults:  { _controller: OCUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout